---
- name: intsall nicita
  hosts: nicita6
  become: yes
  #become_user: bscell
  become_method: sudo
  tasks:
  - name: ping destination
    ping:
  - name: Change TZ to UTC
    timezone:
     name: UTC
  - name: install packs
    yum:
      state: present
      name:
         - strongswan
         - ntp
         - screen
         - nfs-common
         - dos2unix
         - python-pip
         - python3-pip
         - vim
         - gpsd
         - apache2
         - libcurl4-gnutls-dev
         - librtmp-dev
         - python-gtk2
         - dhcpd
         - isc-dhcp-server
         - sshpass
         - curl
         - sqlite3
  - name: Update and upgrade apt packages
    become: true
    apt:
     upgrade: yes
     update_cache: yes
  - name: Remove useless packages from the cache
    become: true
    apt:
     autoclean: yes
  - name: Remove dependencies that are no longer required
    become: true
    apt:
     autoremove: yes
  - name: Extract Tactical-Box.tar.gz into /home/bscell/Downloads/
    unarchive:
     src: /home/bscell/Downloads/Tactical-Box.tar.gz
     dest: /home/bscell/Downloads/
     remote_src: yes
  - name: update install files to unix format
    shell: find . -type f -print0 |xargs -0 dos2unix
    args:
       chdir: /home/bscell/Downloads/Tactical-Box
  - name: Copy a "dhcp config files"
    copy:
      src: /home/bscell/Downloads/Tactical-Box/ConfigFiles/core/dhcpd.conf
      dest: /etc/dhcp/
      remote_src: yes
  - name: Copy a "dhcp config files 2"
    copy:
      src: /home/bscell/Downloads/Tactical-Box/ConfigFiles/core/isc-dhcp-server
      dest: /etc/default
      remote_src: yes
  - name: Enable service isc-dhcp-server
    service:
      name: isc-dhcp-server
      enabled: yes
#####################mongoDB###############################
  - name: Copy mongochef
    copy:
      src: /home/bscell/Downloads/Tactical-Box/mongochef-4.4.2-linux-x64-dist
      dest: /home/bscell
      owner: bscell
      group: bscell
      remote_src: yes
  - name: Create a symbolic link
    file:
      src: /home/bscell/mongochef-4.4.2-linux-x64-dist/bin/mongochef.sh
      dest: /usr/local/bin/mongochef
      owner: bscell
      group: bscell
      state: link
  - file:
     dest: home/bscell/mongochef-4.4.2-linux-x64-dist/jre/bin/
     owner: bscell
     group: bscell
     mode: 777
     recurse: yes
  - name: Add an apt key by id from a keyserver
    apt_key:
     keyserver: keyserver.ubuntu.com
     id: EA312927
  - name: update mongo rep
    shell: echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - name: Install mongodb packages
    become: true
    apt:
      update_cache: yes
      pkg:
      - mongodb-org=3.2.9
      - mongodb-org-server=3.2.9
      - mongodb-org-shell=3.2.9
      - mongodb-org-mongos=3.2.9
      - mongodb-org-tools=3.2.9
      allow_unauthenticated: true
  - name: Enable mongod service
    service:
      name: mongod.service
      enabled: yes
  - name: update mongo
    shell: echo "mongodb-org hold" | sudo dpkg --set-selections && echo "mongodb-org-server hold" | sudo dpkg --set-selections && echo "mongodb-org-shell hold" | sudo dpkg --set-selections && echo "mongodb-org-mongos hold" | sudo dpkg --set-selections && echo "mongodb-org-tools hold" | sudo dpkg --set-selections
  - name: Update mongodb.conf with bind 0.0.0.0
    replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
      backup: no
      ##########################PIP/PIP3############################
    - name: install PIP packages, force upgrade
      pip:
        name:
          - pip
          - virtualenv
          - virtualenvwrapper
          - requests
        state: latest
        executable: pip2

      ###########################need to check if was installed#############
  - name: install PIP3 package, force upgrade
    pip:
      name:
        - pip
        - virtualenv
        - virtualenvwrapper
        - paramiko
      state: latest
      executable: pip3
      #######################################################################
################################################################
  - name: Install   packages
    become: true
    apt:
      update_cache: yes
      pkg:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev
      allow_unauthenticated: true

  - name: Insert a lines to  .bashrc .
    lineinfile:
        path: /home/bscell/.bashrc
        line:
           "export WORKON_HOME=$HOME/.virtualenvs \nsource /usr/local/bin/virtualenvwrapper.sh "
  - name: restart bashrc
    shell: source  /home/bscell/.bashrc
    args:
      warn: no
      executable: /bin/bash

      ##########################################need to do manualy #
      #    • Run “mkvirtualenv --python=/usr/bin/python3.5 bscell”
    #Run “workon bscell” (if it is not already ):
#pip install pycurl
#pip install paramiko
#pip install gps

#deactivate   to exit workon
#############################################################3
  - name: Update all packages to the latest version
    apt:
     upgrade: dist
     update_cache: yes
##########################################
########3need to do automation for net rules file #####################3
  - name: Copy a 70-persistent-net.rules
    copy:
      src: /home/bscell/Downloads/Tactical-Box/70-persistent-net.rules
      dest: /etc/udev/rules.d
      remote_src: yes
  - name: Install build-esential and dkms (prepare)
    apt:
      name:
      - build-essential
      - dkms
      - unzip
      state: present
      update_cache: yes

  - name: Add VirtualBox repo keys
    apt_key:
      url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
      state: present
    with_items:
      - oracle_vbox
      - oracle_vbox_2016

  - name: Add VirtualBox repo
    apt_repository:
      repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian xenial contrib'
      state: present
      update_cache: yes

  - name: "Install virtualbox "
    apt:
      name: virtualbox
      state: present

  - name: Download VirtualBox extension pack
    get_url:
      url: "https://download.virtualbox.org/virtualbox/5.1.38/Oracle_VM_VirtualBox_Extension_Pack-5.1.38.vbox-extpack"
      dest: /tmp/



  - name: Output downloaded VirtualBox extension pack file name
    debug:
      var: download_result.dest
      verbosity: 1

  - name: Install VirtualBox extension pack
    shell: "echo 'y' | VBoxManage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.1.38.vbox-extpack"  
