---
- name: intsall nicita
  hosts: nicita6
  user: bscell
  vars:
     ansible_ssh_private_key_file: /home/graf/.ssh/dankey
     TacticalBoxPack   : Tactical-Box.tar.gz
     VM_image_MITM     : MITM_Core_CB3-P17a.ova
     VM_image_Ubuntu_IP: Ubuntu_IP_New.ova
     VM_image_win      : win_7_64_last.ova
     VM_name_MITM      : MITM_Core_CB3
     VM_name_Ubuntu_IP : buntu_IP
     VM_name_win_7_64  : win_7_64
  #become_user: bscell
  #become_method: sudo
  tasks:


  - name: "Adding user bscell  to the group vboxusers"
    become: yes
    user: name=bscell
          groups=vboxusers
          append=yes

  - name: Copy VMs
    copy:
      src: /home/bscell/Downloads/Tactical-Box/Vbox
      dest: /home/bscell/
      remote_src: yes
      owner: bscell
      group: bscell
      mode: '0777'

  - name: Install MITM_Core VM
    shell: vboxmanage import /home/bscell/Vbox/{{VM_image_MITM}}
    become: true
    become_method: su
    become_user: bscell

  - name: Install Ubuntu IP VM
    shell: vboxmanage import /home/bscell/Vbox/{{VM_image_Ubuntu_IP}}
    become: true
    become_method: su
    become_user: bscell

  - name: Install win_7_64 VM
    shell: vboxmanage import /home/bscell/Vbox/{{VM_image_win}}
    become: true
    become_method: su
    become_user: bscell

  - name: run dos2unix
    shell: cd /home/bscell/Downloads/Tactical-Box/Vbox ; find . -type f -print0 |xargs -0 dos2unix
    become: true


  - name: Copy vbox config files
    become: true
    copy:
     src: /home/bscell/Downloads/Tactical-Box/Vbox/virtualbox
     dest: /etc/default/
     remote_src: yes
     mode: '0777'


  - name:  create directory /etc/vbox/
    become: true
    file:
      path: /etc/vbox
      state: directory
      mode: '0775'
      recurse: yes



  - name: Copy vbox config files 2
    become: true
    copy:
      src: /home/bscell/Downloads/Tactical-Box/Vbox/vbox.cfg
      dest: /etc/vbox/
      remote_src: yes
      mode: '0777'

  - name: Touch a file, bscell.stop
    become: true
    file:
      path: /etc/vbox/bscell.stop
      state: touch
      owner: bscell
      group: vboxusers
      mode: '0777'

  - name: Touch a file, bscell.start
    become: true
    file:
      path: /etc/vbox/bscell.start
      state: touch
      owner: bscell
      group: vboxusers
      mode: '0777'

  - name: Recursively change ownership of a directory
    become: true
    file:
      path: /etc/vbox
      state: directory
      recurse: yes
      group: vboxusers
      mode: '1775'

  - name: modify user group
    shell: usermod -a -G vboxusers bscell
    become: true

  - name: setproperty autostartdbpath
    shell: VBoxManage setproperty autostartdbpath /etc/vbox



  - name: modifyvm "MITM_Core_CB3"
    shell: VBoxManage modifyvm "MITM_Core_CB3" --autostart-enabled on


  - name: modifyvm "Ubuntu_IP"
    shell: VBoxManage modifyvm "Ubuntu_IP" --autostart-enabled on


  - name: modifyvm "win_7_64"
    shell: VBoxManage modifyvm "win_7_64" --autostart-enabled on


  - name: define Host only net
    shell: VBoxManage hostonlyif create ; VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.2.1 --netmask 255.255.255.0
