---
- name: intsall nicita
  hosts: nicita6
  user: bscell
  vars:
     ansible_ssh_private_key_file: /home/graf/.ssh/dankey
  #become_user: bscell
  become_method: sudo
  tasks:
  - name: ping destination
    ping:
